### ISSUE TITLE
Missing `PAN_BUNDLE_TYPE` in file `pan-cn-mgmt-configmap.yaml`

### ISSUE THREAD

**Issue by devsecfranklin** [PaloAltoNetworks/cn-series-helm#14]
## Describe the bug

Missing `PAN_BUNDLE_TYPE` in file `pan-cn-mgmt-configmap.yaml`

## Current behavior

Bundle type is missing from template. 

## Possible solution

Set `PAN_BUNDLE_TYPE` like so with a CN-X-BND1 or CN-X-BND2 style license:
(look at last line) 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc
  PAN_MGMT_SECRET: pan-mgmt-secret

  # Panorama settings
  PAN_PANORAMA_IP: "44.124.31.336"
  PAN_DEVICE_GROUP: "gke-cluster-device group"
  PAN_TEMPLATE_STACK: "gke-cluster-franklin"
  PAN_CGNAME: "gke-cluster-cg"
  PAN_BUNDLE_TYPE: "CN-X-BND2"
```

## Context

You will have an issue connecting to cluster from Kubernetes plug in in Panorama.

## Your Environment

I am using:

- Panorama 10.0.7
- Kubernetes plug in 1.0.2
- CN series images: https://console.cloud.google.com/gcr/images/gcp-gcs-pso/us/paloaltonetworks?authuser=1&project=gcp-gcs-pso

- Link to your project: https://github.com/devsecfranklin/gke-cluster/
